### ISSUE TITLE
Output the results of our diffing in a reasonable format.

### ISSUE THREAD

**Issue by Ian9802** [PolicyStat/gitlit#105]
It should be reasonable, if not a little heavy, before we have minimized the diffing.

**Comment by satchwsm** [comment]
![whiteboard](https://cloud.githubusercontent.com/assets/2292952/5812345/77f9395c-a036-11e4-936b-79cb110c473f.jpg)
![screenshot from 2015-01-19 23 51 46](https://cloud.githubusercontent.com/assets/2292952/5812347/863371ea-a036-11e4-8015-5422bb90be2e.png)

Earlier this week we discussed an optimal diff output to be used for tested, UI, and working toward in our algorithm

**Comment by timaeudg** [comment]
should have been closed by #122
