### ISSUE TITLE
Investigate using gitlet for git via javascript

### ISSUE THREAD

**Issue by kylegibson** [PolicyStat/gitlit#112]
There's a relatively new project called coincidentally called "gitlet" 

https://github.com/maryrosecook/gitlet

**Comment by Ian9802** [comment]
If we wish o stop using git and start using gitlet as our vc this is an option.

**Comment by satchwsm** [comment]
Introducing this library to the project and removing our dependency on shelling out to git could be an improvement to the project, and seems like a good candidate for the refactoring and bug fixing work we are required to do for our spring quarter. I propose adding this as a task to be completed in that phase of the project, after feature implementation is more fleshed out.

She implements init, add, rm, commit, branch, checkout, diff, remote, fetch, merge, push, pull, status and clone all of which would be useful in developing more complex features.

In playing around with this library a little, the output for diffs are pretty nice for what we need. 

>FILE_STATUS: { ADD: "A", MODIFY: "M", DELETE: "D", SAME: "SAME", CONFLICT: "CONFLICT" },

>Diffs
>are represented as JS objects that map file paths to objects that
> indicate the change required to get from the first version of the
> file (the receiver) to the second (the giver).  eg:
> <pre>{
>   file1: {
>     status: "A",
>     receiver: undefined,
>     base: undefined,
>     giver: hash(1)
>   },
>   file2: {
>     status: "C",
>     receiver: hash(b),
>     base: hash(a),
>     giver: hash(c)
>   }
> }</pre>

Where the output given for repo 'a' between versions 4e1e3bd2 and 6cec0a49 on master is:

>satchwsm@doombringer:~/Documents/Courses/seniorproject/gitlit/a$ gitlet diff 4e1e3bd2 6cec0a49
>M ../cli/code.html

**Comment by timaeudg** [comment]
This could be useful, the only thing we have to be wary, it may be, and in fact seems that gitlet can't commit and push to Git repositories, but instead operates on Gitlet repositories, which is important to consider.

Anyway, we are still a bit away from that, so we still have time to consider whether this is what we want
